/**
 * Party.jsx  (Customers)
 * ──────────────────────
 * Level-1 view: customer list with add / edit / delete.
 * Clicking a row drills down to CustomerDetail.
 *
 * Rules enforced (unchanged):
 *   • ID is auto-generated by DB — never shown in form, never sent on create
 *   • CUST_TYPE DB values: "Local" | "International"  (sent as-is)
 *   • STATUS DB values: Integer 1 (Active) / 0 (Inactive) — converted in party.js
 *   • PARTY STATUS DB values: String "Active" | "Inactive"  (sent as-is)
 *   • All fields are compulsory — form blocks save until every field is filled
 *   • IDs displayed are raw DB numeric IDs (no S-xxx / MP-xxx formatting)
 *
 * What moved out:
 *   • ContactsModal     → party/ContactsModal.jsx  (owns ["contacts", id] query)
 *   • CustomerDetail    → party/CustomerDetail.jsx  (+ DetailRow, DetailSection)
 *   • CustomerFormFields → party/CustomerFormFields.jsx  (+ SectionLabel, ErrMsg)
 *   • TypeBadge, Field  → party/partyShared.jsx
 *   • validateFields    → party/partyValidation.js
 *   • All constants     → party/partyConstants.js
 */

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  getCustomers, createCustomer, updateCustomer, deleteCustomer,
} from "../../api/party";
import {
  PAGE_SIZE,
  thStyle, tdBase, tdNowrap,
} from "./shared/adminStyles";
import { TableScroller, Pagination } from "./shared/AdminTable";
import { useToast } from "./shared/ToastContext";
import Btn       from "./shared/Btn";
import StatusDot from "./shared/StatusDot";

// ── Sub-components & helpers from party/ ─────────────────────────────────────
import { TypeBadge }           from "./party/partyShared";
import { validateFields }      from "./party/partyValidation";
import {
  UPPERCASE_FIELDS,
  CUSTOMER_REQUIRED, INTL_REQUIRED,
  EMPTY_CUSTOMER,
} from "./party/partyConstants";
import CustomerDetail      from "./party/CustomerDetail";
import CustomerFormFields  from "./party/CustomerFormFields";

export default function Party({ role }) {
  const toast = useToast();
  const queryClient = useQueryClient();

  // ── Query ──────────────────────────────────────────────────
  const { data: customers = [], isLoading: loading, isError: customersError } = useQuery({
    queryKey: ["customers"],
    queryFn:  () => getCustomers().then(data =>
      [...data].sort((a, b) => b.id - a.id),
    ),
  });

  // ── UI state ───────────────────────────────────────────────
  const [view, setView]               = useState("list"); // "list" | "detail" | "form"
  const [page, setPage]               = useState(1);
  const [editingCustomer, setEditingCustomer] = useState(null);
  const [detailCustomer, setDetailCustomer]   = useState(null);
  const [form, setForm]               = useState(EMPTY_CUSTOMER);
  const [formErr, setFormErr]         = useState("");
  const [fieldErrors, setFieldErrors] = useState({});
  const [saving, setSaving]           = useState(false);
  const [sameAddress, setSameAddress] = useState(false); // "same as buyer address" checkbox

  const canEdit = role === "SUPER" || role === "ADMIN";
  const canAdd  = role === "SUPER" || role === "ADMIN" || role === "COMMON";

  // ── Navigation ─────────────────────────────────────────────
  const openDetail = (customer) => { setDetailCustomer(customer); setView("detail"); };

  const openForm = (customer = null) => {
    setEditingCustomer(customer);
    setForm(customer ? { ...EMPTY_CUSTOMER, ...customer } : EMPTY_CUSTOMER);
    setFormErr(""); setFieldErrors({}); setSameAddress(false);
    setView("form");
  };

  // ── Field change helpers ───────────────────────────────────
  // Handles uppercase auto-conversion and per-field error clearing.
  const fco = (field, val) => {
    const v = UPPERCASE_FIELDS.has(field) ? val.toUpperCase() : val;
    setForm(prev => ({ ...prev, [field]: v }));
    setFieldErrors(prev => ({ ...prev, [field]: undefined }));
  };

  // Address variant: also syncs shipping when "same as buyer" is active.
  const fcoAddr = (field, val) => {
    setForm(prev => {
      const next = { ...prev, [field]: val };
      if (sameAddress) {
        if (field === "buyerAddress1") next.shippingAddress1 = val;
        if (field === "buyerAddress2") next.shippingAddress2 = val;
        if (field === "buyerAddress3") next.shippingAddress3 = val;
      }
      return next;
    });
    setFieldErrors(prev => ({ ...prev, [field]: undefined }));
  };

  const handleSameAddress = (checked) => {
    setSameAddress(checked);
    if (checked) {
      setForm(prev => ({
        ...prev,
        shippingAddress1: prev.buyerAddress1,
        shippingAddress2: prev.buyerAddress2,
        shippingAddress3: prev.buyerAddress3,
      }));
    }
  };

  // ── Save ───────────────────────────────────────────────────
  const saveCustomer = async () => {
    const required = [
      ...CUSTOMER_REQUIRED,
      ...(form.customerType === "International" ? INTL_REQUIRED : []),
    ];
    const { errors, isValid } = validateFields(form, required);
    setFieldErrors(errors);
    if (!isValid) {
      setFormErr("");
      const msgs = Object.values(errors);
      toast.error(msgs.length === 1 ? msgs[0] : `${msgs.length} validation errors — fix highlighted fields.`);
      return;
    }
    setSaving(true); setFormErr(""); setFieldErrors({});
    try {
      if (editingCustomer) {
        const u = await updateCustomer(editingCustomer.id, form);
        queryClient.setQueryData(["customers"], (prev = []) =>
          prev.map(c => c.id === u.id ? u : c),
        );
        setDetailCustomer(u);
        setView("detail");
      } else {
        const c = await createCustomer(form);
        queryClient.setQueryData(["customers"], (prev = []) =>
          [...prev, c].sort((a, b) => b.id - a.id),
        );
        setView("list");
      }
    } catch (e) {
      toast.error(e.message);
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ─────────────────────────────────────────────────
  const deleteC = async (customer) => {
    try {
      await deleteCustomer(customer.id);
      queryClient.setQueryData(["customers"], (prev = []) =>
        prev.filter(c => c.id !== customer.id),
      );
      setView("list");
    } catch (e) {
      toast.error(e.message);
    }
  };

  const pagedCustomers = customers.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const isIntl = form.customerType === "International";

  // ══════════════════════════════════════════════════════════
  // ── Detail view
  // ══════════════════════════════════════════════════════════
  if (view === "detail" && detailCustomer) {
    return (
      <CustomerDetail
        customer={detailCustomer}
        role={role}
        onBack={() => setView("list")}
        onEdit={(c) => openForm(c)}
        onDelete={() => deleteC(detailCustomer)}
      />
    );
  }

  // ══════════════════════════════════════════════════════════
  // ── Form view (Add / Edit)
  // ══════════════════════════════════════════════════════════
  if (view === "form") {
    return (
      <div className="content-section">
        <Btn variant="back" onClick={() => editingCustomer ? setView("detail") : setView("list")} icon="←">
          ← {editingCustomer ? `Back to ${editingCustomer.companyName}` : "Back to Customers"}
        </Btn>

        <div style={{
          marginTop: 16, background: "var(--a-surface-solid)", borderRadius: 12,
          border: "1px solid var(--a-border-card)", padding: "20px 18px", maxWidth: 860,
        }}>
          <div style={{ marginBottom: 20 }}>
            <h2 style={{ margin: 0, fontSize: "1.15rem", fontWeight: 700, color: "var(--a-teal)" }}>
              {editingCustomer ? `Edit — ${editingCustomer.companyName}` : "Add Customer"}
            </h2>
            <p style={{ margin: "4px 0 0", fontSize: "0.78rem", color: "var(--a-text-muted)" }}>
              All fields marked <span style={{ color: "var(--a-danger)" }}>*</span> are required.
              GST, PAN, TAN, CIN &amp; IFSC auto-uppercase as you type.
              {/* ID is auto-generated by the database — not shown in this form */}
            </p>
          </div>

          <CustomerFormFields
            form={form}
            onChange={fco}
            onAddressChange={fcoAddr}
            sameAddress={sameAddress}
            onSameAddressChange={handleSameAddress}
            errors={fieldErrors}
            isIntl={isIntl}
            formErr={formErr}
          />

          <div style={{ display: "flex", gap: 10, marginTop: 20 }}>
            <Btn variant="primary" onClick={saveCustomer} disabled={saving}>
              {saving ? "Saving…" : editingCustomer ? "Update Customer" : "Add Customer"}
            </Btn>
            <Btn variant="ghost" onClick={() => editingCustomer ? setView("detail") : setView("list")}>
              Cancel
            </Btn>
          </div>
        </div>
      </div>
    );
  }

  // ══════════════════════════════════════════════════════════
  // ── List view
  // ══════════════════════════════════════════════════════════
  return (
    <div className="content-section">
      <div className="activity-header">
        <div>
          <h1 style={{ margin: 0, fontSize: "1.6rem", fontWeight: 700, color: "var(--a-teal)" }}>
            Customers
          </h1>
          <p style={{ margin: "4px 0 0", fontSize: "0.85rem", color: "var(--a-text-muted)" }}>
            Click any row to view full details &amp; manage contacts
          </p>
        </div>
        {canAdd && (
          <Btn variant="teal" onClick={() => openForm()} icon="＋">+ Add Customer</Btn>
        )}
      </div>

      <div style={{
        background: "var(--a-surface-solid)", borderRadius: 12,
        border: "1px solid var(--a-border-card)", overflow: "hidden",
      }}>
        {loading ? (
          <p className="loading" style={{ padding: 40 }}>Loading…</p>
        ) : (
          <>
            <TableScroller>
              <table style={{ width: "100%", minWidth: 680, borderCollapse: "collapse" }}>
                <thead>
                  <tr>
                    {/* ID column = raw DB auto-generated numeric ID */}
                    {["ID", "COMPANY NAME", "CONTACT", "EMAIL", "GST", "TYPE", "STATUS"].map(h => (
                      <th key={h} style={thStyle}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {customers.length === 0 ? (
                    <tr>
                      <td colSpan={7} className="activity-empty">
                        {customersError
                          ? "Failed to load customers. Please try again."
                          : canEdit
                          ? 'No customers found. Click "+ Add Customer" to create one.'
                          : "No customers found."}
                      </td>
                    </tr>
                  ) : pagedCustomers.map((customer, idx) => (
                    <tr
                      key={customer.id}
                      onClick={() => openDetail(customer)}
                      style={{
                        background: idx % 2 === 1 ? "var(--a-teal-04, rgba(20,184,166,0.04))" : "transparent",
                        cursor: "pointer", transition: "background 0.1s",
                      }}
                      onMouseEnter={e => { e.currentTarget.style.background = "var(--a-teal-10)"; }}
                      onMouseLeave={e => { e.currentTarget.style.background = idx % 2 === 1 ? "var(--a-teal-04, rgba(20,184,166,0.04))" : "transparent"; }}
                      title="Click to view details"
                    >
                      {/* Raw DB auto-generated ID — no S-xxx / MP-xxx formatting */}
                      <td style={{ ...tdBase, color: "var(--a-teal)", fontWeight: 700 }}>{customer.id}</td>
                      <td style={{ ...tdBase, fontWeight: 600 }}>
                        <span style={{ display: "inline-flex", alignItems: "center", gap: 5 }}>
                          {customer.companyName}
                          <span style={{ fontSize: "0.7rem", color: "var(--a-teal)", opacity: 0.6 }}>›</span>
                        </span>
                      </td>
                      <td style={tdNowrap}>{customer.contactNumber}</td>
                      <td style={tdBase}>{customer.email}</td>
                      <td style={{
                        ...tdBase,
                        fontFamily: "var(--font-mono, monospace)", fontSize: "0.8rem",
                        color: customer.gst ? "var(--a-text)" : "var(--a-text-faint)",
                      }}>
                        {customer.gst || "—"}
                      </td>
                      <td style={tdBase}><TypeBadge type={customer.customerType} /></td>
                      <td style={tdBase}><StatusDot status={customer.status} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </TableScroller>
            <Pagination total={customers.length} page={page} onChange={setPage} />
            <div style={{
              padding: "8px 16px", color: "var(--a-text-faint)", fontSize: "0.75rem",
              borderTop: customers.length > 0 ? "1px solid var(--a-teal-08)" : "none",
            }}>
              {customers.length} customer{customers.length !== 1 ? "s" : ""}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
