/**
 * employeeOnboarding.js
 * ─────────────────────
 * Employee Onboarding Link Module — API wrapper.
 *
 * Authenticated (Super User / Admin) endpoints:
 *   GET    /api/employee-onboarding                 → list all requests
 *   GET    /api/employee-onboarding/{id}             → single request detail
 *   POST   /api/employee-onboarding                  → create a new link   (SUPER only)
 *   DELETE /api/employee-onboarding/{id}              → revoke a pending link (SUPER only)
 *   POST   /api/employee-onboarding/{id}/approve      → approve + create employee (SUPER only)
 *   POST   /api/employee-onboarding/{id}/reject       → reject with a reason (SUPER only)
 *
 * Public (no auth) endpoints — used by the tokenized employee-facing form:
 *   GET    /api/employee-onboarding/public/{token}         → check link validity / load draft
 *   POST   /api/employee-onboarding/public/{token}/submit  → submit employee details
 *
 * NOTE: whichever frontend route you wire up for the public form (e.g.
 * "/onboard/:token") should read the token from the URL and pass it to
 * getPublicOnboarding()/submitPublicOnboarding() below. ONBOARDING_ROUTE_PREFIX
 * is exported so the link generated by CreateLinkModal always matches it.
 */

import { authHeaders, mutationFetch } from "./_auth";
import { BASE_URL } from "./_base";

// Change this if you mount the public onboarding form at a different path.
export const ONBOARDING_ROUTE_PREFIX = "/onboard";

async function safeJson(res) {
  const text = await res.text();
  try { return text ? JSON.parse(text) : {}; } catch { return {}; }
}

async function readError(res, fallback) {
  const body = await safeJson(res);
  return new Error(body.error || body.message || fallback);
}

/** Builds the full shareable onboarding link for a given token. */
export function buildOnboardingLink(token) {
  return `${window.location.origin}${ONBOARDING_ROUTE_PREFIX}/${token}`;
}

// ── Authenticated — management side ─────────────────────────────────────────

export async function getOnboardingLinks(status) {
  const qs  = status ? `?status=${encodeURIComponent(status)}` : "";
  const res = await fetch(`${BASE_URL}/api/employee-onboarding${qs}`, { headers: authHeaders() });
  if (!res.ok) throw await readError(res, "Failed to fetch onboarding requests.");
  const list = await res.json();
  return Array.isArray(list) ? list : [];
}

export async function getOnboardingLink(id) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding/${id}`, { headers: authHeaders() });
  if (!res.ok) throw await readError(res, "Failed to fetch onboarding request.");
  return res.json();
}

/** hours: e.g. 1 (1 hour), 24 (1 day), 168 (7 days), or any custom value. */
export async function createOnboardingLink(hours) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding`, {
    method: "POST", headers: authHeaders(),
    body: JSON.stringify({ hours }),
  });
  if (!res.ok) throw await readError(res, "Failed to create onboarding link.");
  return res.json();
}

export async function revokeOnboardingLink(id) {
  const res = await mutationFetch(`${BASE_URL}/api/employee-onboarding/${id}`, "DELETE");
  if (!res.ok) throw await readError(res, "Failed to revoke onboarding link.");
  return safeJson(res);
}

export async function approveOnboarding(id) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding/${id}/approve`, {
    method: "POST", headers: authHeaders(),
  });
  if (!res.ok) throw await readError(res, "Failed to approve onboarding request.");
  return res.json();
}

export async function rejectOnboarding(id, reason) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding/${id}/reject`, {
    method: "POST", headers: authHeaders(),
    body: JSON.stringify({ reason }),
  });
  if (!res.ok) throw await readError(res, "Failed to reject onboarding request.");
  return res.json();
}

// ── Public — employee-facing form (NO auth headers) ─────────────────────────

export async function getPublicOnboarding(token) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding/public/${token}`);
  if (!res.ok) throw await readError(res, "This link is invalid or has expired.");
  return res.json();
}

export async function submitPublicOnboarding(token, data) {
  const res = await fetch(`${BASE_URL}/api/employee-onboarding/public/${token}/submit`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) {
    const body = await safeJson(res);
    const err  = new Error(body.error || "Failed to submit your details.");
    err.fieldErrors = body.errors || null;
    throw err;
  }
  return res.json();
}
