/**
 * party.js
 * ─────────
 * Customer CRUD + Party (contacts) CRUD
 * Talks to Java backend on port 8080
 *
 * DB columns (CUSTOMER_DETAILS):
 *   ID (auto), NAME, CONTACT, GMAIL_ID, WEBSITE,
 *   CUST_TYPE ("Local" | "International"),
 *   GST, CIN, PAN, TAN, C_GSTLUTNO,
 *   BUYER_ADDRESS_1/2/3, SHIPPING_ADDRESS_1/2/3,
 *   BANKACCHOLDER, BANKNAME, ACCNUMBER, MICRCODE, IFSCCODE,
 *   C_SWIFT_CODE, C_BANKCODE, C_IBAN,
 *   C_BANKBRANCH_ADD_1/2/3,
 *   STATUS (Integer: 1 = Active, 0 = Inactive),
 *   DATECREATED (auto)
 *
 * DB columns (PARTY_DIRECTORY):
 *   ID (auto), CUSTOMER_ID, PARTY_NAME, PARTY_PHONENO,
 *   PARTY_EMAIL, STATUS (String: "Active" | "Inactive"),
 *   DATECREATED (auto)
 */

import { authHeaders, mutationFetch } from "./_auth";

import { BASE_URL } from "./_base";

async function safeJson(res) {
  const text = await res.text();
  try { return text ? JSON.parse(text) : {}; } catch { return {}; }
}

async function handleResponse(res, fallbackMsg) {
  const data = await safeJson(res);
  if (!res.ok) throw new Error(data.message || fallbackMsg);
  return data;
}

// ── Customer status helpers ──────────────────────────────────────────────────
// DB CUSTOMER_DETAILS.STATUS column: Integer  1 = Active, 0 = Inactive
const statusToInt   = (s) => (s === "Active" ? 1 : 0);
const statusFromInt = (n) => (n === 1 || n === "1" ? "Active" : "Inactive");

// ── Customer field mapping ───────────────────────────────────────────────────
// Maps backend DTO fields ↔ frontend form fields.
// DB actual values:
//   CUST_TYPE  → "Local" | "International"  (stored as-is, default "Local")
//   STATUS     → Integer 1 / 0

function fromCustomerDTO(dto) {
  if (!dto) return dto;
  return {
    id:               String(dto.id),
    // Basic info
    companyName:      dto.name             || "",
    contactNumber:    dto.contact          || "",
    email:            dto.gmailId          || "",
    website:          dto.website          || "",
    // DB CUST_TYPE stores "Local" or "International" — use those exact strings
    customerType:     dto.custType         || "Local",
    gst:              dto.gst              || "",
    cin:              dto.cin              || "",
    pan:              dto.pan              || "",
    tan:              dto.tan              || "",
    status:           statusFromInt(dto.status),
    cGstLutNo:        dto.cGstLutNo        || "",
    // Buyer address
    buyerAddress1:    dto.buyerAddress1    || "",
    buyerAddress2:    dto.buyerAddress2    || "",
    buyerAddress3:    dto.buyerAddress3    || "",
    // Shipping address
    shippingAddress1: dto.shippingAddress1 || "",
    shippingAddress2: dto.shippingAddress2 || "",
    shippingAddress3: dto.shippingAddress3 || "",
    // Bank details
    bankAccHolder:    dto.bankAccHolder    || "",
    bankName:         dto.bankName         || "",
    accountNumber:    dto.accNumber        || "",   // DB col: ACCNUMBER
    micrCode:         dto.micrCode         || "",
    ifscCode:         dto.ifscCode         || "",
    cSwiftCode:       dto.cSwiftCode       || "",
    cBankCode:        dto.cBankCode        || "",
    cIban:            dto.cIban            || "",
    cBankBranchAdd1:  dto.cBankBranchAdd1  || "",
    cBankBranchAdd2:  dto.cBankBranchAdd2  || "",
    cBankBranchAdd3:  dto.cBankBranchAdd3  || "",
  };
}

function toCustomerDTO(data) {
  return {
    // Do NOT include id — auto-generated by DB
    name:             data.companyName      || "",
    contact:          data.contactNumber    || "",
    gmailId:          data.email            || "",
    website:          data.website          || "",
    // Send exact DB value: "Local" or "International"
    custType:         data.customerType     || "Local",
    gst:              data.gst              || "",
    cin:              data.cin              || "",
    pan:              data.pan              || "",
    tan:              data.tan              || "",
    status:           statusToInt(data.status),
    cGstLutNo:        data.cGstLutNo        || "",
    buyerAddress1:    data.buyerAddress1    || "",
    buyerAddress2:    data.buyerAddress2    || "",
    buyerAddress3:    data.buyerAddress3    || "",
    shippingAddress1: data.shippingAddress1 || "",
    shippingAddress2: data.shippingAddress2 || "",
    shippingAddress3: data.shippingAddress3 || "",
    bankAccHolder:    data.bankAccHolder    || "",
    bankName:         data.bankName         || "",
    accNumber:        data.accountNumber    || "",  // DB col: ACCNUMBER
    micrCode:         data.micrCode         || "",
    ifscCode:         data.ifscCode         || "",
    cSwiftCode:       data.cSwiftCode       || "",
    cBankCode:        data.cBankCode        || "",
    cIban:            data.cIban            || "",
    cBankBranchAdd1:  data.cBankBranchAdd1  || "",
    cBankBranchAdd2:  data.cBankBranchAdd2  || "",
    cBankBranchAdd3:  data.cBankBranchAdd3  || "",
  };
}

// ── Party (contact) field mapping ────────────────────────────────────────────
// DB PARTY_DIRECTORY columns: ID (auto), CUSTOMER_ID, PARTY_NAME,
//   PARTY_PHONENO, PARTY_EMAIL, STATUS (String), DATECREATED (auto)

function fromPartyDTO(dto) {
  if (!dto) return dto;
  return {
    id:           String(dto.id),
    customerId:   String(dto.customerId   || ""),
    customerName: dto.customerName || "",
    name:         dto.partyName    || "",
    phone:        dto.partyPhoneno || "",
    email:        dto.partyEmail   || "",
    // DB STATUS column stores "Active" or "Inactive" as-is
    status:       dto.status       || "Active",
  };
}

function toPartyDTO(customerId, data) {
  return {
    // Do NOT include id — auto-generated by DB
    customerId:   Number(customerId),
    partyName:    data.name   || "",
    partyPhoneno: data.phone  || "",
    partyEmail:   data.email  || "",
    status:       data.status || "Active",
  };
}

// ── Customer CRUD ────────────────────────────────────────────────────────────

export async function getCustomers() {
  const res = await fetch(`${BASE_URL}/api/customers`, { headers: authHeaders() });
  const list = await handleResponse(res, "Failed to fetch customers");
  return Array.isArray(list) ? list.map(fromCustomerDTO) : [];
}

export async function createCustomer(data) {
  const res = await fetch(`${BASE_URL}/api/customers`, {
    method: "POST", headers: authHeaders(),
    body: JSON.stringify(toCustomerDTO(data)),
  });
  return fromCustomerDTO(await handleResponse(res, "Failed to create customer"));
}

export async function updateCustomer(id, data) {
  const res = await mutationFetch(`${BASE_URL}/api/customers/${id}`, "PUT", {
    body: JSON.stringify(toCustomerDTO(data)),
  });
  return fromCustomerDTO(await handleResponse(res, "Failed to update customer"));
}

export async function deleteCustomer(id) {
  const res = await mutationFetch(`${BASE_URL}/api/customers/${id}`, "DELETE");
  return handleResponse(res, "Failed to delete customer");
}

// ── Party (contacts) CRUD ────────────────────────────────────────────────────

// GET /api/customers/{customerId}/parties
export async function getContacts(customerId) {
  const res = await fetch(`${BASE_URL}/api/customers/${customerId}/parties`, {
    headers: authHeaders(),
  });
  const list = await handleResponse(res, "Failed to fetch parties");
  return Array.isArray(list) ? list.map(fromPartyDTO) : [];
}

// POST /api/parties
export async function createContact(customerId, data) {
  const res = await fetch(`${BASE_URL}/api/parties`, {
    method: "POST", headers: authHeaders(),
    body: JSON.stringify(toPartyDTO(customerId, data)),
  });
  return fromPartyDTO(await handleResponse(res, "Failed to create party"));
}

// PUT /api/parties/{id}
export async function updateContact(id, customerId, data) {
  const res = await mutationFetch(`${BASE_URL}/api/parties/${id}`, "PUT", {
    body: JSON.stringify(toPartyDTO(customerId, data)),
  });
  return fromPartyDTO(await handleResponse(res, "Failed to update party"));
}

// DELETE /api/parties/{id}
export async function deleteContact(id) {
  const res = await mutationFetch(`${BASE_URL}/api/parties/${id}`, "DELETE");
  return handleResponse(res, "Failed to delete party");
}
